build_from:
  armhf: zachowj/xfinity-data-usage:v0.17.8
  armv7: zachowj/xfinity-data-usage:v0.17.8
  aarch64: zachowj/xfinity-data-usage:v0.17.8
  amd64: zachowj/xfinity-data-usage:v0.17.8
  i386: zachowj/xfinity-data-usage:v0.17.8
