name: Xfinity Data Usage
version: 0.27.1
slug: xfinity_data_usage
description: >-
  Fetch Xfinity data usage and serve it via an HTTP endpoint, publish it to MQTT
  or post it to an URL.
arch:
  - armhf
  - aarch64
  - amd64
  - i386
startup: system
boot: auto
options: {}
services:
  - mqtt:need
schema:
  xfinity:
      username: str
      password: str
  mqtt:
    host: str
    port: 1883
    username: str
    password: str
    topic: str
    homeassistant:
      prefix: str
ports:
  7878/tcp: 17878
ports_description:
  7878/tcp: REST sensor
map:
  - 'config:rw'
environment:
  TZ: US/Mountain
  LOGGING_LEVEL: debug
  CONFIG_FOLDER: /config/xfinity-data-usage
